:PROPERTIES:
:ID:       24f36df4-2735-4424-abde-69b0b77a6bb3
:END:
#+title: Introduction to Sets
#+filetags: :lecture:
* Definitions
** Set
A *set* is a well-defined collection of distinct objects. An object in a set is called an *element* of the set or is said to *belong* to the set.

If an object \(x\) is an element of a set \(A\), this is denoted by \(x \in A\).

If an object \(x\) is not a member of a set \(A\), this is denoted by \(x \notin A\).

Notation: "\(\in\)" means "is an element of".

** Empty Set
The *empty set*, denoted by \(\emptyset\) or \(\varnothing\), is the unique set that has no elements.

** Subsets
Let \(A\) and \(B\) be sets.
1. \(A\) is a *subset* of \(B\), denoted \(A \subseteq B \iff \forall a \in A, a \in B\)
2. \(A\) is a *proper subset* of \(B\), denoted \(A \subsetneq B \iff \exists x \in B\) so that \(x \notin A\).
3. \(A\) and \(B\) are *equal* \(\iff A \subseteq B\) and \(B \subseteq A\).
4. The *power set* of \(A\) is the set \(\mathcal{P}(A)\) whose elements are the subsets of \(A\)

  \[\mathcal{P}(A) = \{U : U \subseteq A\}\]


* Lecture Notes
We describe a set by telling what are its elements.

* Key Concepts
We also use curly brackets to describe a set.
\(A=\{1, 2, 5, 7\}\)

\(B=\{x \in \mathbb{Z} : x^{2}+3x-1 \le 0\}\)
- \(B\) is the set of all integers such that \(x^{2}+3x-1 \le 0\).
  \(2 \in B\) because \({(-2)}^{2}+3{(-2)}-1 = 3 \le 0\).

* Examples
\(\mathbb{Q}\): The set of all rational numbers.

\(\mathbb{Z}\): The set of all integers.

\(\mathbb{R}\): The set of all real numbers.

\(\mathbb{C}\): The set of all complex numbers.

* Related Concepts
- [[id:71d0c22e-b7e7-4dfe-ab4b-89736fd69161][Rational & Irrational Numbers]]
